from django.urls import path
from .views import index, login_user, register_user, save_test_result


urlpatterns = [
    path('', index),
    path('login_user/', login_user, name='login_user'),
    path('register_user/', register_user, name='register_user'),
    path('test-results/create/', save_test_result, name='test-result-create'),

    path('login/', index),
    path('register/', index),
    path('test1/', index),
    path('test2/', index),
    path('test3/', index),
    path('test4/', index),
    path('test5/', index),
    path('attention-test/', index),
    path('reaction-test/', index),
    path('memory-test/', index),
    path('text-selection-test/', index),
    path('sum-digits-test/', index),
    path('test1ilya/', index),
    path('test2ilya/', index),
    path('test3ilya/', index),
    path('test4ilya/', index),
    path('test5ilya/', index),
    path('rectangles/', index),
    path('twelve-number-test/', index),
    path('numbers-puzzle/', index),
    path('reaction-speed/', index),
    path('classical-stroop-test/', index),
    path('test1mitya/', index),
    path('test2mitya/', index),
    path('test3mitya/', index),
    path('test4mitya/', index),
    path('test5mitya/', index),
    path('test1k/', index),
    path('test2k/', index),
    path('test3k/', index),
]
