# Generated by Django 5.1.6 on 2025-02-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_testresult_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testnsi',
            name='title_all',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testnsi',
            name='title_correct',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
