# Generated by Django 5.1.6 on 2025-03-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='try_number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
